[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
declare_id_test = "4zWMoR3G5hhUY4V51JXvxuCw255D9zeoGRd4dBNJtma6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/nazreen.mohamad/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
